---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    author: don
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    type: appserver
...